import { Provider } from '@angular/core';
import {
  LucideArrowRight,
  LucideArrowUpRight,
  LucideBoxes,
  LucideCheck,
  LucideCheckCircle2,
  LucideChevronDown,
  LucideChevronRight,
  LucideCircleDot,
  LucideCopy,
  LucideDatabase,
  LucideDownload,
  LucideFileText,
  LucideFolderGit2,
  LucideGitBranch,
  LucideKey,
  LucideLayers,
  LucideLayoutDashboard,
  LucideLink2,
  LucideLoader2,
  LucideMaximize2,
  LucideMessageSquare,
  LucideMinimize2,
  LucideMoreHorizontal,
  LucideNetwork,
  LucidePencil,
  LucidePlus,
  LucideRefreshCw,
  LucideSearch,
  LucideSend,
  LucideSlidersHorizontal,
  LucideSparkles,
  LucideTable,
  LucideTrash2,
  LucideUpload,
  LucideX,
  LucideZoomIn,
  LucideZoomOut,
  provideLucideIcons,
} from '@lucide/angular';

export const APP_LUCIDE_ICONS = [
  LucideGitBranch,
  LucideKey,
  LucideLayoutDashboard,
  LucideDatabase,
  LucideChevronDown,
  LucideChevronRight,
  LucideLayers,
  LucideSparkles,
  LucideNetwork,
  LucideMessageSquare,
  LucideFolderGit2,
  LucideArrowUpRight,
  LucideBoxes,
  LucideArrowRight,
  LucidePlus,
  LucideSearch,
  LucideSend,
  LucideSlidersHorizontal,
  LucideCircleDot,
  LucideCheckCircle2,
  LucideTable,
  LucidePencil,
  LucideTrash2,
  LucideUpload,
  LucideFileText,
  LucideMoreHorizontal,
  LucideDownload,
  LucideCopy,
  LucideRefreshCw,
  LucideLink2,
  LucideLoader2,
  LucideX,
  LucideCheck,
  LucideZoomIn,
  LucideZoomOut,
  LucideMaximize2,
  LucideMinimize2,
] as const;

export function provideAppIcons(): Provider {
  return provideLucideIcons(...APP_LUCIDE_ICONS);
}

export { LucideDynamicIcon as DynamicIcon } from '@lucide/angular';
